name: tasbeeh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.1
  flutter_advanced_drawer: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/click.wav

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/Lato-Black.ttf

